var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Content-Type,Content-Length, Authorization, Accept,X-Requested-With");
  res.header("Access-Control-Allow-Methods","PUT,POST,GET,DELETE,OPTIONS");
  res.header("X-Powered-By",' 3.2.1')
  res.json([[{
    "weekname":"5周",
    "allMoney":1800,
    "days":[
        {"day":'周一',"money":400}, 
        {"day":'周二',"money":30},
        {"day":'周三',"money":200},
        {"day":'周四',"money":100},
        {"day":'周五',"money":560},
        {"day":'周六',"money":170},
        {"day":'周日',"money":40}],
    "anyone":[
       {"iconname":"icon-gouwu","name":"购物","money":170},
       {"iconname":"icon-huankuan","name":"还款","money":40},
       {"iconname":"icon-yule","name":"娱乐","money":100},
        {"iconname":"icon-jiaotong","name":"交通","money":30},
       {"iconname":"icon-rolled","name":"日常","money":200},
       {"iconname":"icon-shuazi","name":"美容","money":560},
       {"iconname":"icon-tongxun","name":"通讯","money":400}
    ]
},{
    "weekname":"上周",
    "allMoney":1400,
    "days":[
        {"day":'周一',"money":100}, 
        {"day":'周二',"money":560},
        {"day":'周三',"money":200},
        {"day":'周四',"money":400},
        {"day":'周五',"money":30},
        {"day":'周六',"money":170},
        {"day":'周日',"money":40}],
    "anyone":[
        {"iconname":"icon-jiaotong","name":"交通","money":30},
       {"iconname":"icon-rolled","name":"日常","money":200},
       {"iconname":"icon-shuazi","name":"美容","money":560},
       {"iconname":"icon-tongxun","name":"通讯","money":400},
       {"iconname":"icon-gouwu","name":"购物","money":170},
       {"iconname":"icon-huankuan","name":"还款","money":40},
       {"iconname":"icon-yule","name":"娱乐","money":100}
    ]
},{
    "weekname":"本周",
    "allMoney":700,
    "days":[
        {"day":'周一',"money":15}, 
        {"day":'周二',"money":85},
        {"day":'周三',"money":200},
        {"day":'周四',"money":100},
        {"day":'周五',"money":50},
        {"day":'周六',"money":280},
        {"day":'周日',"money":20}],
    "anyone":[
       {"iconname":"icon-tongxun","name":"通讯","money":200},
       {"iconname":"icon-gouwu","name":"购物","money":85},
       {"iconname":"icon-rolled","name":"日常","money":100},
       {"iconname":"icon-huankuan","name":"还款","money":20},
       {"iconname":"icon-yule","name":"娱乐","money":50},
       {"iconname":"icon-shuazi","name":"美容","money":280},
        {"iconname":"icon-jiaotong","name":"交通","money":15}
    ]
}],[{
    "weekname":"1月",
    "allMoney":4000,
    "days":[
        {"day":'1',"money":100}, 
        {"day":'2',"money":560},
        {"day":'3',"money":200},
        {"day":'4',"money":400},
        {"day":'5',"money":30},
        {"day":'6',"money":170},
        {"day":'7',"money":40},
        {"day":'8',"money":100}, 
        {"day":'9',"money":560},
        {"day":'10',"money":200},
        {"day":'11',"money":400},
        {"day":'12',"money":30},
        {"day":'13',"money":170},
        {"day":'14',"money":40},
        {"day":'15',"money":100}, 
        {"day":'16',"money":560},
        {"day":'17',"money":200},
        {"day":'18',"money":400},
        {"day":'19',"money":30},
        {"day":'20',"money":170},
        {"day":'21',"money":40},
        {"day":'22',"money":100}, 
        {"day":'23',"money":560},
        {"day":'24',"money":200},
        {"day":'25',"money":400},
        {"day":'26',"money":30},
        {"day":'27',"money":170},
        {"day":'28',"money":40}],
    "anyone":[
        {"iconname":"icon-jiaotong","name":"交通","money":30},
       {"iconname":"icon-rolled","name":"日常","money":200},
       {"iconname":"icon-shuazi","name":"美容","money":560},
       {"iconname":"icon-tongxun","name":"通讯","money":400},
       {"iconname":"icon-gouwu","name":"购物","money":170},
       {"iconname":"icon-huankuan","name":"还款","money":40},
       {"iconname":"icon-yule","name":"娱乐","money":100}
    ]
},{
    "weekname":"上月",
    "allMoney":18888,
    "days":[
        {"day":'1',"money":50}, 
        {"day":'2',"money":360},
        {"day":'3',"money":200},
        {"day":'4',"money":400},
        {"day":'5',"money":30},
        {"day":'6',"money":170},
        {"day":'7',"money":40},
        {"day":'8',"money":100}, 
        {"day":'9',"money":260},
        {"day":'10',"money":200},
        {"day":'11',"money":20},
        {"day":'12',"money":30},
        {"day":'13',"money":170},
        {"day":'14',"money":40},
        {"day":'15',"money":100}, 
        {"day":'16',"money":560},
        {"day":'17',"money":200},
        {"day":'18',"money":400},
        {"day":'19',"money":30},
        {"day":'20',"money":170},
        {"day":'21',"money":40},
        {"day":'22',"money":100}, 
        {"day":'23',"money":150},
        {"day":'24',"money":200},
        {"day":'25',"money":200},
        {"day":'26',"money":30},
        {"day":'27',"money":170},
        {"day":'28',"money":40}],
    "anyone":[
        {"iconname":"icon-jiaotong","name":"交通","money":30},
       {"iconname":"icon-rolled","name":"日常","money":200},
       {"iconname":"icon-shuazi","name":"美容","money":560},
       {"iconname":"icon-tongxun","name":"通讯","money":400},
       {"iconname":"icon-gouwu","name":"购物","money":170},
       {"iconname":"icon-huankuan","name":"还款","money":40},
       {"iconname":"icon-yule","name":"娱乐","money":100}
    ]
},{
    "weekname":"本月",
    "allMoney":10086,
    "days":[
        {"day":'1',"money":150}, 
        {"day":'2',"money":460},
        {"day":'3',"money":200},
        {"day":'4',"money":100},
        {"day":'5',"money":130},
        {"day":'6',"money":170},
        {"day":'7',"money":40},
        {"day":'8',"money":100}, 
        {"day":'9',"money":60},
        {"day":'10',"money":500},
        {"day":'11',"money":20},
        {"day":'12',"money":130},
        {"day":'13',"money":170},
        {"day":'14',"money":40},
        {"day":'15',"money":100}, 
        {"day":'16',"money":60},
        {"day":'17',"money":20},
        {"day":'18',"money":100},
        {"day":'19',"money":30},
        {"day":'20',"money":170},
        {"day":'21',"money":40},
        {"day":'22',"money":100}, 
        {"day":'23',"money":150},
        {"day":'24',"money":210},
        {"day":'25',"money":20},
        {"day":'26',"money":30},
        {"day":'27',"money":170},
        {"day":'28',"money":40}],
    "anyone":[
       {"iconname":"icon-tongxun","name":"通讯","money":200},
       {"iconname":"icon-gouwu","name":"购物","money":85},
       {"iconname":"icon-rolled","name":"日常","money":100},
       {"iconname":"icon-huankuan","name":"还款","money":20},
       {"iconname":"icon-yule","name":"娱乐","money":50},
       {"iconname":"icon-shuazi","name":"美容","money":280},
        {"iconname":"icon-jiaotong","name":"交通","money":15}
    ]
}],[{
    "weekname":"去年",
    "allMoney":8888,
    "days":[
        {"day":'1',"money":15}, 
        {"day":'2',"money":25},
        {"day":'3',"money":20},
        {"day":'4',"money":100},
        {"day":'5',"money":150},
        {"day":'6',"money":180},
        {"day":'7',"money":20},
        {"day":'8',"money":85},
        {"day":'9',"money":180},
        {"day":'10',"money":100},
        {"day":'11',"money":250},
        {"day":'12',"money":80}],
    "anyone":[
        {"iconname":"icon-jiaotong","name":"交通","money":30},
       {"iconname":"icon-rolled","name":"日常","money":200},
       {"iconname":"icon-shuazi","name":"美容","money":560},
       {"iconname":"icon-tongxun","name":"通讯","money":400},
       {"iconname":"icon-gouwu","name":"购物","money":170},
       {"iconname":"icon-huankuan","name":"还款","money":40},
       {"iconname":"icon-yule","name":"娱乐","money":100}
    ]
},{
    "weekname":"今年",
    "allMoney":6666,
    "days":[
        {"day":'1',"money":15}, 
        {"day":'2',"money":85},
        {"day":'3',"money":200},
        {"day":'4',"money":100},
        {"day":'5',"money":50},
        {"day":'6',"money":280},
        {"day":'7',"money":20},
        {"day":'8',"money":85},
        {"day":'9',"money":200},
        {"day":'10',"money":100},
        {"day":'11',"money":50},
        {"day":'12',"money":280}],
    "anyone":[
       {"iconname":"icon-tongxun","name":"通讯","money":200},
       {"iconname":"icon-gouwu","name":"购物","money":85},
       {"iconname":"icon-rolled","name":"日常","money":100},
       {"iconname":"icon-huankuan","name":"还款","money":20},
       {"iconname":"icon-yule","name":"娱乐","money":50},
       {"iconname":"icon-shuazi","name":"美容","money":280},
        {"iconname":"icon-jiaotong","name":"交通","money":15}
    ]
}]]);
});

module.exports = router;
